RosterBuilder/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("users/", include("users.urls", namespace="users")),
    path("builder/", include("builder.urls", namespace="builder"))
]

builder/urls.py
from django.urls import path

from .views import RosterListView, DisplayRosterListView, FactionUnitsListView, CreateRosterView, \
    ManageRosterListView, RosterDeleteView

app_name = "builder"

urlpatterns = [
    path("roster_list/", RosterListView.as_view(), name="roster_list"),
    path("display_roster/<int:pk>", DisplayRosterListView.as_view(), name="display_roster"),
    path("manage_roster/<int:pk>", ManageRosterListView.as_view(), name="manage_roster"),
    path("units_list/", FactionUnitsListView.as_view(), name="units_list"),
    path("units_list/<int:pk>", FactionUnitsListView.as_view(), name="units_list"),
    path("roster_create/", CreateRosterView.as_view(), name="roster_create"),
    path("delete_roster/<int:pk>", RosterDeleteView.as_view(), name="delete_roster"),
]

users/urls.py
from django.urls import path

from .views import UserView, UserLoginView, UserProfileView, logout, UserRegisterView

app_name = "users"

urlpatterns = [
    path("", UserView.as_view(), name="user"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", logout, name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("register/", UserRegisterView.as_view(), name="register"),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class NormalUser(AbstractUser):
	first_name = models.CharField('first name', max_length=150)
	last_name = models.CharField('last name', max_length=150)
	email = models.EmailField('email address', unique=True)


class UserProfile(models.Model):
	rosters_count = models.PositiveIntegerField("total roser count", default=0)
	user = models.OneToOneField(NormalUser, on_delete=models.CASCADE, db_index=True)

	def __str__(self):
		return f"{self.user} profile"

	@receiver(post_save, sender=NormalUser)
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			UserProfile.objects.create(user=instance)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from .models import NormalUser

class UserLoginForm(AuthenticationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))

	class Meta:
		model = NormalUser
		fields = ("username", "password")

class UserUpdateForm(UserChangeForm):
	username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))

	class Meta:
		model = NormalUser
		fields = ("username", "first_name", "last_name", "email")

class UserCreateForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))

	class Meta:
		model = NormalUser
		fields = ("username", "first_name", "last_name", "email")

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import View, UpdateView, CreateView
from django.contrib.auth.views import LoginView
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserLoginForm, UserUpdateForm, UserCreateForm
from .models import NormalUser, UserProfile

# Create your views here.

class UserView(View):
	template_name = "users/base.html"

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name)

class UserLoginView(LoginView):
	template_name = "users/login.html"
	form_class = UserLoginForm
	success_url = "users:profile"

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return HttpResponseRedirect(reverse_lazy(self.success_url))
		return super(UserLoginView, self).get(request, *args, **kwargs)


class UserProfileView(LoginRequiredMixin, UpdateView):
	model = NormalUser
	template_name = "users/profile.html"
	form_class = UserUpdateForm

	def get(self, request, *args, **kwargs):
		self.object = NormalUser.objects.get(pk=request.user.id)
		context = self.get_context_data(**kwargs)

		# условие для суперюзера, т.к. для него нет соответстующей таблицы
		if not request.user.is_superuser:
			context["rosters_count"] = UserProfile.objects.get(user=request.user.id).rosters_count

		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = self.form_class(data=request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse("users:profile"))


class UserRegisterView(CreateView):
	model = NormalUser
	template_name = "users/register.html"
	form_class = UserCreateForm

	def get_success_url(self):
		return reverse_lazy("users:profile")



def logout(request):
	auth.logout(request)
	return HttpResponseRedirect(reverse("users:login"))

def index(request):
	return render(request, "users/index.html")

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    {% block additional_styles %}
    {% endblock %}
    <title>
        Roster Builder
    </title>
</head>
<header>
    <div class="navbar navbar-expand-lg bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Roster builder</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">About project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'builder:units_list' %}">Avaliable factions</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Features
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Roster building</a></li>
                        <li><a class="dropdown-item" href="#">Import your rosters</a></li>
                        <li><a class="dropdown-item" href="#">Export your rosters</a></li>
                        <li><a class="dropdown-item" href="#">Roster statistic analyzer</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Additional features for registered users</a></li>
                    </ul>
                </li>
            </ul>
            <div class="row">
                {% if user.is_authenticated %}
                    <div class="col pt-1 text-nowrap">You are: {{ user.username }}</div>
                    <a type="button" class="col me-3 my-auto btn btn-primary btn-sm" href="{% url 'users:profile' %}">Profile</a>
                    <a type="button" class="col me-3 my-auto btn btn-primary btn-sm" href="{% url 'builder:roster_list' %}">Rosters</a>
                    <a type="button" class="col me-3 my-auto btn btn-primary btn-sm" href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                    <div class="col pt-1 text-nowrap">You are: Guest</div>
                    <a type="button" class="col me-3 btn btn-primary btn-sm" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<body>
{% block content %}
{% endblock %}
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
{% block additional_scripts %}
{% endblock %}

users/templates/users/index.html
{% extends "users/base.html" %}

{% block content %}
<div>This is index page</div>
{% endblock %}

users/templates/users/login.html
{% extends "users/base.html" %}

{% block content %}

<div class="container">
  <div class="card shadow-lg border-0 rounded-lg mt-5">
      <div class="card-header"><h3 class="text-center font-weight-light my-2">Авторизация</h3>
      </div>
      <div class="card-body">

          <form class="row g-3 align-items-center" action="{% url 'users:login' %}" method="POST">
              {% csrf_token %}
              <div>
                  <label class="form-label col-auto" for="{{ form.username.id_for_label }}">User name</label>
                  {{ form.username }}
              </div>
              <div>
                  <label class="form-label col-auto" for="{{ form.password.id_for_label }}">Password</label>
                  {{ form.password }}
              </div>
              <div class="form-group d-flex justify-content-center flex-column align-items-center">
                    <input class="btn btn-primary" type="submit" value="Authorize">
                  <div>
                      <a href="#">Forgot password?</a>
                      <a href="{% url 'users:register' %}">Register account?</a>
                  </div>

              </div>
          </form>

      </div>
  </div>
</div>


{% endblock %}

users/templates/users/profile.html
{% extends "users/base.html" %}

{% block content %}

<div class="container">
  <h3 class="text-center font-weight-light my-2">Profile</h3>
  <form action="{% url 'users:profile' %}" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col">
      <label class="form-label" for="{{ form.username.id_for_label }}">User name</label>
        {{ form.username }}
      </div>
      <div class="col">
      <label class="form-label" for="{{ form.email.id_for_label }}">Email</label>
      {{ form.email }}
    </div>
    </div>

    <div class="row">
      <div class="col">
        <label class="form-label" for="{{ form.first_name.id_for_label }}">First name</label>
        {{ form.first_name }}
      </div>
      <div class="col">
        <label class="form-label" for="{{ form.last_name.id_for_label }}">Last name</label>
        {{ form.last_name }}
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label class="form-label" for="r_count">Rosters count:</label>
        <input type="text" class="form-control" id="r_count" disabled value="{{ rosters_count }}">
      </div>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <input class="btn btn-primary btn-lg" type="submit" value="Save">
    </div>
  </form>
</div>



{% endblock %}

users/templates/users/register.html
{% extends "users/base.html" %}

{% block content %}

<div class="container">
    <h3 class="text-center font-weight-light my-2">Registration</h3>
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <label class="form-label" for="{{ form.username.id_for_label }}">User name</label>
                {{ form.username }}
            </div>
            <div class="col">
                <label class="form-label" for="{{ form.email.id_for_label }}">Email</label>
                {{ form.email }}
            </div>

        </div>
        <div class="row">
            <div class="col">
                <label class="form-label" for="{{ form.first_name.id_for_label }}">First name</label>
                {{ form.first_name }}
            </div>
            <div class="col">
                <label class="form-label" for="{{ form.last_name.id_for_label }}">Last name</label>
                {{ form.last_name }}
            </div>

        </div>
        <div class="row">
            <div class="col">
                <label class="form-label" for="{{ form.password1.id_for_label }}">Password</label>
                {{ form.password1 }}
            </div>
            <div class="col">
                <label class="form-label" for="{{ form.password2.id_for_label }}">Repeat Password</label>
                {{ form.password2 }}
            </div>
        </div>
        <div class="d-flex justify-content-center mt-2">
            <input class="btn btn-primary btn-lg" type="submit" value="Save">
        </div>

    </form>
</div>
{% endblock %}