RosterBuilder/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("users/", include("users.urls", namespace="users")),
    path("builder/", include("builder.urls", namespace="builder"))
]

builder/urls.py
from django.urls import path

from .views import RosterListView, DisplayRosterListView, FactionUnitsListView, CreateRosterView, \
    ManageRosterListView, RosterDeleteView

app_name = "builder"

urlpatterns = [
    path("roster_list/", RosterListView.as_view(), name="roster_list"),
    path("display_roster/<int:pk>", DisplayRosterListView.as_view(), name="display_roster"),
    path("manage_roster/<int:pk>", ManageRosterListView.as_view(), name="manage_roster"),
    path("units_list/", FactionUnitsListView.as_view(), name="units_list"),
    path("units_list/<int:pk>", FactionUnitsListView.as_view(), name="units_list"),
    path("roster_create/", CreateRosterView.as_view(), name="roster_create"),
    path("delete_roster/<int:pk>", RosterDeleteView.as_view(), name="delete_roster"),
]

users/urls.py
from django.urls import path

from .views import UserView, UserLoginView, UserProfileView, logout, UserRegisterView

app_name = "users"

urlpatterns = [
    path("", UserView.as_view(), name="user"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", logout, name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("register/", UserRegisterView.as_view(), name="register"),

]

builder/forms.py
from django import forms

from .models import Roster, CodexFaction

class NewRosterForm(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	max_cost = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}))
	description = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
	factions = forms.MultipleChoiceField(choices=[[faction.pk, faction.name] for faction in CodexFaction.objects.all()])

	class Meta:
		model = Roster
		fields = ("name", "max_cost", "description", "factions")

builder/views.py
import json

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.http import JsonResponse
from django.db.models import Q
from django.db import connection

from .models import Roster, Unit, UnitsCountRestrictions, CodexFaction,  Weapon, UnitModelProfile, WeaponProfile, Detachment
from .forms import NewRosterForm
from users.models import NormalUser


def get_all_units_data(faction_ids):
    final_data = []
    for faction_id in faction_ids:
        all_units = Unit.objects.filter(codex_faction=faction_id)
        for unit in all_units:
            result = {
                "unit": unit,
                "models": None,
                "weapons": None,
                "abilities": None,
                "other_wargear": None,
            }

            restrictions = UnitsCountRestrictions.objects.select_related("unit").select_related("unit_model").filter(
                unit=unit.pk)
            all_models = []
            for restr in restrictions:
                all_models.append(
                    {
                        "model": restr.unit_model,
                        "profiles": sorted(UnitModelProfile.objects.filter(unit_model=restr.unit_model),
                                           key=lambda el: el.position),
                        "count": 0,
                        "count_restrictions": {"min": restr.minimum_count, "max": restr.maximum_count}
                    }
                )
            result["models"] = all_models

            all_weapons = []
            weapons = Weapon.objects.filter(u_weapon=unit)
            for weapon in weapons:
                    all_weapons.append(
                        {
                            "weapon": weapon,
                            "profiles": WeaponProfile.objects.filter(weapon=weapon),
                            "count": 0,
                        }
                    )
            result["weapons"] = all_weapons

            all_abilities = []
            abilities = unit.abilities.all()
            for ability in abilities:
                all_abilities.append(
                    {
                        "ability": ability,
                        "bought": True
                    }
                )
            result["abilities"] = all_abilities

            all_wargear = []
            wargear = unit.other_wargear.all()
            for wgr in wargear:
                all_wargear.append(
                    {
                        "wargear": wgr,
                        "count": 0
                    }
                )
            result["other_wargear"] = all_wargear

            final_data.append(result)
    return final_data


def unpack_roster_data(roster):
    return json.loads(roster.roster_data.decode())

def extract_models(unit_dict):
    all_models = []
    restrictions = UnitsCountRestrictions.objects.select_related("unit").select_related("unit_model").filter(
        unit=unit_dict["unit_pk"])

    for restr in restrictions:
        for model in unit_dict["models"]:
            if model["model_pk"] == restr.unit_model.pk:
                all_models.append(
                    {
                        "model": restr.unit_model,
                        "profiles": sorted(UnitModelProfile.objects.filter(unit_model=restr.unit_model), key=lambda el: el.position),
                        "count": model["model_count"],
                        "count_restrictions": {"min": restr.minimum_count, "max": restr.maximum_count}
                    }
                )
    return all_models

def extract_weapons(unit_dict, unit_obj):
    all_weapons = []
    weapons = Weapon.objects.filter(u_weapon=unit_obj)

    # ПРОТЕСТИРОВАТЬ СОКРАЩЕНИЕ КОЛ-ВА ЗАПРОСОВ
    # weapons = Weapon.objects.prefetch_related("wp_weapon").filter(u_weapon=unit_obj)

    for weapon in weapons:
        for w_entry in unit_dict["weapons"]:
            if w_entry["weapon_pk"] == weapon.pk:
                all_weapons.append(
                    {
                        "weapon": weapon,
                        "profiles": WeaponProfile.objects.filter(weapon=weapon),
                        "count": w_entry["weapon_count"],
                    }
                )
    return all_weapons

def extract_abilities(unit_dict, unit_obj):
    all_abilities = []
    abilities = unit_obj.abilities.all()
    for ability in abilities:
        for a_entry in unit_dict["abilities"]:
            if a_entry["ability_pk"] == ability.pk:
                all_abilities.append(
                    {
                        "ability": ability,
                        "bought": a_entry["bought"]
                    }
                )
    return all_abilities

def extract_other_wargear(unit_dict, unit_obj):
    all_wargear = []
    wargear = unit_obj.other_wargear.all()
    for wgr in wargear:
        for w_entry in unit_dict["other_wargear"]:
            if w_entry["wargear_pk"] == wgr.pk:
                all_wargear.append(
                    {
                        "wargear": wgr,
                        "count": w_entry["wargear_count"]
                    }
                )
    return all_wargear

def get_roster_context(roster):
    data = unpack_roster_data(roster)
    final_data = {
            "detachment_data": [Detachment.objects.get(pk=det_pk) for det_pk in data["detachment_data"]],
            "main_data": []
        }

    for unit in data["main_data"]:
        result = {
            "position_number": unit["position_number"],
            "unit": None,
            "models": None,
            "weapons": None,
            "abilities": None,
            "other_wargear": None,
        }

        unit_obj = Unit.objects \
            .select_related("codex_faction") \
            .get(pk=unit["unit_pk"])
        result["unit"] = unit_obj
        result["models"] = extract_models(unit)
        result["weapons"] = extract_weapons(unit, unit_obj)
        result["abilities"] = extract_abilities(unit, unit_obj)
        result["other_wargear"] = extract_other_wargear(unit, unit_obj)
        final_data["main_data"].append(result)
    return final_data


class FactionUnitsListView(ListView):
    template_name = "builder/units_list.html"

    def get(self, request, *args, **kwargs):
        all_factions = CodexFaction.objects.all()
        all_units = {}
        if kwargs:
            if faction_pk := kwargs["pk"]:
                all_units = {
                    "HQ": [],
                    "Troops": [],
                    "Dedicated_Transport": [],
                    "Elites": [],
                    "Fast_Attack": [],
                    "Flyers": [],
                    "Heavy_Support": [],
                    "Lords_of_War": []
                }
                faction = CodexFaction.objects.get(id=faction_pk)
                units = Unit.objects.filter(codex_faction=faction)
                for unit in units:
                    all_units[unit.battlefield_role.name.replace(" ", "_")].append(
                        {
                            "unit": unit,
                            "model_restrictions": UnitsCountRestrictions.objects.filter(unit=unit)
                        }
                    )

        return render(
            request, self.template_name, {
                "all_units": all_units, "factions": all_factions})


class RosterListView(ListView):
    template_name = "builder/roster_list.html"

    def get(self, request, *args, **kwargs):
        return render(
            request, self.template_name, {
                "rosters": Roster.objects.prefetch_related("factions").filter(user=request.user.pk),
            }
        )


class DisplayRosterListView(ListView):
    template_name = "builder/display_roster.html"

    def get(self, request, *args, **kwargs):
        roster = Roster.objects.get(pk=kwargs["pk"])
        context = get_roster_context(roster)
        return render(
            request,
            self.template_name,
            {
                "roster": roster,
                "detachments": context["detachment_data"],
                "units_list": sorted(context["main_data"], key=lambda x: x["position_number"])
            }
        )

class ManageRosterListView(ListView):
    template_name = "builder/manage_roster.html"

    def get(self, request, *args, **kwargs):
        roster = Roster.objects.get(pk=kwargs["pk"])
        context = get_roster_context(roster)

        return render(
            request,
            self.template_name,
            {
                "all_faction_units": get_all_units_data([faction.id for faction in roster.factions.all()]), #Unit.objects.filter(codex_faction=1),
                "roster": roster,
                "detachments": context["detachment_data"],
                "units_list": sorted(context["main_data"], key=lambda x: x["position_number"]),
                "all_detachments": Detachment.objects.all(),
                'data': json.dumps({"data_1": 33, "data_2": "mydata"})
            }
        )

    def post(self, request, *args, **kwargs):
        request_data = json.loads(request.body.decode())
        total_cost = request_data.pop("total_cost")
        roster = Roster.objects.get(pk=request_data["roster_id"])
        roster.total_cost = total_cost
        roster.roster_data = json.dumps(request_data["data"]).encode()
        roster.save()
        return JsonResponse({"status": 200, "text": "OK"})


class CreateRosterView(CreateView):
    template_name = "builder/roster_create.html"
    model = Roster
    form_class = NewRosterForm
    success_url = "builder:roster_list"

    def get_context_data(self, **kwargs):
        return {"factions": CodexFaction.objects.all(), "form": self.form_class}

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():

builder/templates/builder/roster_create.html
{% extends "users/base.html" %}
{% load static %}

{% block additional_styles %}
{% endblock %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <form action="{% url 'builder:roster_create' %}" method="post">
            {% csrf_token %}
            <div class="container">
                <div class="row">
                    <div class="col">
                        <label class="form-label" for="{{ form.name.id_for_label }}">Roster name</label>
                        {{ form.name }}
                    </div>
                    <div class="col">
                        <label class="form-label" for="{{ form.max_cost.id_for_label }}">Max points</label>
                        {{ form.max_cost }}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label class="form-label" for="{{ form.description.id_for_label }}">Description</label>
                        {{ form.description }}
                    </div>
                </div>
                <div class="row">
                    <div class="text-center mt-3 mb-3">Factions</div>
                    <div class="col d-flex justify-content-center">
                        <label class="form-label" for="{{ form.factions.id_for_label }}"></label>
                        {{ form.factions }}
                    </div>
                </div>
<!--                <div class="text-center mt-3">Factions</div>-->
<!--                <div class="d-flex flex-wrap justify-content-around mt-3 border border-2 rounded">-->
<!--                    {% for faction in factions %}-->
<!--                        <div class="form-check m-3">-->
<!--                            <input class="form-check-input" type="checkbox" value="{{ faction.id }}" id="factions">-->
<!--                            <label class="form-check-label" for="{{ faction.name }}">-->
<!--                            {{ faction.name }}-->
<!--                            </label>-->
<!--                        </div>-->
<!--                    {% endfor %}-->
<!--                </div>-->

                <div class="d-flex justify-content-center mt-2">
                    <input class="btn btn-primary btn-lg" type="submit" value="Create">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block additional_scripts %}
{% endblock %}

builder/templates/builder/roster_list.html
{% extends "users/base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row border border-2 border-secondary">
        <div class="col-3 border d-flex justify-content-center">
            <div class="m-3 align-text-center"><b>User:</b> {{ user.username }}</div>
        </div>
        <div class="col border d-flex justify-content-center">
            <div class="m-3 align-text-center"><b>Statistics:</b> Total rosters: {{ rosters.count }}</div>
        </div>
        <div class="col-3 d-flex justify-content-around align-items-center">
            <div>
                <a type="button" class="col me-3 align-self-center btn btn-primary" href="{% url 'builder:roster_create' %}">Create roster</a>
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-around m-3 flex-wrap">
    {% for roster in rosters %}
        <div class="border border-4 border-dark mw-50 rounded">
            <div class="p-2">
                <div><b>Name:</b> <a style="text-decoration: none;" href="{% url 'builder:display_roster' roster.pk %}">{{ roster.name }}</a></div>
                <div>
                    <b>Factions:</b>
                    {% if roster.factions.all %}
                        {% for faction in roster.factions.all %}
                            {% if forloop.last %}
                                <span>{{ faction.name }}.</span>
                            {% else %}
                                <span>{{ faction.name }}, </span>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        -
                    {% endif %}
                </div>
                <div><b>Description:</b> {{ roster.description }}</div>
                <div><b>Points:</b> {{ roster.total_cost }}/{{ roster.max_cost }}</div>
                <div><b>Privacy:</b> {% if roster.private %}Private{% else %}Public{% endif %}</div>
            </div>
            <div class="border-top d-flex p-1 justify-content-around">
                <div class="p-1">
                    <a type="button" class="col btn btn-primary" href="{% url 'builder:manage_roster' roster.pk %}">Edit roster</a>
                </div>
                <div class="p-1">
                    <a type="button" class="col btn btn-primary" href="{% url 'builder:delete_roster' roster.pk %}">Delete roster</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

builder/templates/builder/units_list.html
{% extends "users/base.html" %}
{% load static %}
{% load custom_tags %}

{% block additional_styles %}
    <link rel="stylesheet" href="{% static 'css/units_list.css' %}"/>
{% endblock %}

{% block content %}
<div>
    <div class="faction_links_wrapper">
        {% for faction in factions %}
            <a class="faction_link" href="{% url 'builder:units_list' faction.pk %}">{{ faction.name }}</a>
        {% endfor %}
    </div>
    {% for b_role, unit_data in all_units.items %}
        {% if unit_data %}
            <h3 class="role">{{ b_role|replace_with_space:"_" }}</h3>
            <div class="units_wrapper">
            {% for element in unit_data %}
                <div class="unit_card">
                    <div class="card_header">Unit</div>
                    <div class="unit_field"><span class="field_name">Unit name:</span>  {{ element.unit.name }}</div>
                    <div class="unit_field"><span class="field_name">Unit battlefield role:</span> {{ element.unit.battlefield_role.name }}</div>
                    <div class="unit_field"><span class="field_name">Unit description:</span> {{ element.unit.description }}</div>
                    <div class="card_header">Models</div>
                    {% for restriction in element.model_restrictions %}
                        <div class="unit_field"><span class="field_name">Model name:</span> {{ restriction.unit_model.name }}</div>
                        <div class="unit_field"><span class="field_name">Price:</span> {{ restriction.unit_model.price }}</div>
                        <div class="unit_field"><span class="field_name">Count restrictions:</span> {{ restriction.minimum_count }}-{{ restriction.maximum_count }}</div>
                        {% for profile in restriction.unit_model.get_profiles %}
                            <div>
                                M - {{ profile.movement }}"|
                                WS - {{ profile.weapon_skill }}|
                                BS - {{ profile.ballistic_skill }}|
                                S - {{ profile.strength }}|
                                T - {{ profile.toughness }}|
                                W - {{ profile.wounds }}|
                                A - {{ profile.attacks }}|
                                Ld - {{ profile.leadership }}|
                                Sv - {{ profile.saving_throw }}+|
                                Base - {{ profile.base }}|
                            </div>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endfor %}
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

{% block additional_scripts %}
{% endblock %}